online_academy/courses/urls.py
from django.urls import path
from . import views

app_name = 'courses'

urlpatterns = [
    path('', views.available_courses, name='courses_list'),
    path('<int:courses_pk>/<int:lesson_pk>/', views.lesson_detail, name='lesson_detail'),
    path('<int:pk>/', views.courses_detail, name='course_detail'),
]

online_academy/online_academy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

urlpatterns = [
    path('courses/', include('courses.urls')),
    path('admin/', admin.site.urls),
    path('', views.hello_world, name='home'),
]

urlpatterns += staticfiles_urlpatterns()

online_academy/courses/models.py
from django.db import models

class Courses(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=30)
    description = models.TextField()

    def __str__(self):
        return self.title
    
class Lessons(models.Model):
    title = models.CharField(max_length=30)
    description = models.TextField()
    content = models.TextField(blank=True, default='')
    order = models.IntegerField(default=0)
    course = models.ForeignKey(Courses, on_delete=models.CASCADE)

    class Meta:
        ordering = ['order', ]

    def __str__(self):
        return self.title

online_academy/courses/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Courses, Lessons

def available_courses(request):
    courses_list = Courses.objects.all()
    email = 'noe2gracida@hotmail.com'
    return render(request, 'courses/course_list.html', {'courses':courses_list, 'email':email})

def courses_detail(request, pk):
    course = get_object_or_404(Courses, pk=pk)
    return render(request, 'courses/course_detail.html', {'course': course})

def lesson_detail(request, courses_pk, lesson_pk):
    lesson = get_object_or_404(Lessons, course_id=courses_pk, pk=lesson_pk)
    return render(request, 'courses/lesson_detail.html', {'lesson': lesson})

online_academy/online_academy/views.py
from django.shortcuts import render
from django.http import HttpResponse

def hello_world(request):
    return render(request, 'home.html')

online_academy/courses/templates/courses/course_detail.html
{% extends "layout.html" %}
{% load humanize course_extras %}


{% block title %} {{ course.title }} {% endblock %}

{% block content %}
<article>
    <h2>{{ course.title }}</h2>
    <p>{{ course.description }}</p>
    <p>We have {{ course.lessons_set.count|apnumber }} lesson{{ course.lessons_set.count|pluralize }} constituting this course: {{ course.lessons_set.all|join:", " }}</p>

    <section>
        {% for lesson in course.lessons_set.all %}
            <h3>
                <a href="{% url 'courses:lesson_detail' courses_pk=lesson.course.pk lesson_pk=lesson.pk %}"> {{ lesson.title }} </a>
            </h3>
            {{ lesson.description|markdown_to_html }}
        {% endfor %}
    </section>
</article>
{% endblock %}

online_academy/courses/templates/courses/course_list.html
{% extends "layout.html"%}

{% load static %}

{% block static %}
    <link rel="stylesheet" href="{% static 'courses/css/courses.css' %}">
{% endblock %}

{% block title %}Available courses{% endblock %}

{% block content %}

<div class="cards">
    
    {% for course in courses %}
        <div class="card">
            <header><a href="{% url 'courses:course_detail' pk=course.pk %}">{{ course.title }}</a></header>
            <div class="card-copy">
                {% if course.description|wordcount <= 10 %}
                    {{ course.description }}
                {% else %}
                    {{ course.description|truncatewords:10 }}
                    <a href="{% url 'courses:course_detail' pk=course.pk %}">Read more</a>
                {% endif %}
                <div>Created at: {{ course.created_at|date:"d/m/yy" }}</div>
            </div>
        </div>
    {% endfor %}
</div>
<div>Contact: {{ email|urlize }}</div>

{% endblock %}

online_academy/courses/templates/courses/lesson_detail.html
{% extends "layout.html" %}
{% load course_extras %}


{% block title %} {{ lesson.title }} - {{ lesson.courses.title }} {% endblock %}

{% block content %}
<article>
    <h2>
        <a href="{% url 'courses:course_detail' pk=lesson.course.pk %}">{{ lesson.course.title }}</a>

    </h2>
    <h3> {{ lesson.title }} </h3>
    {% with content=lesson.content %}
        {{ content|linebreaks }}
        Content: {{ content|wordcount }} words. Estimated time: {{ content|wordcount|time_estimate }} minute{{ content|wordcount|time_estimate|pluralize }}.
    {% endwith %}

</article>

{% endblock %}

online_academy/online_academy/templates/home.html
{% extends "layout.html" %}

{% block title %}Online Academy{% endblock %}

{% block content %}
    <h3>Welcome to Online Academy!!</h3>
{% endblock %}

online_academy/online_academy/templates/layout.html
{% load static from static %}
{% load course_extras %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'css/layout.css' %}">
        {% block static %} {% endblock %}
    </head>
    <body>
        <div class="site-container">
            <nav>
                <a href="{% url 'home' %}">Online Academy</a>
                <a href="{% url 'courses:courses_list' %}">Cursos</a>
            </nav>
            <p>Don't miss our latest course: {% last_course %}</p>
            {% block content %}{% endblock %}    
        </div>
        
    </body>

</html>